name: Go

on:
  push:
    branches: [ main ]
  release:
    types: [ published, created ]

jobs:

  build-macos:
    name: Build macOS version
    runs-on: macos-11.0
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: ./build.js

  build-linux:
    name: Build Linux version
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: ./build.js

  publish-release:
    name: Publish release
    needs: [ build-macos, build-linux ]
    runs-on: ubuntu-latest
    steps:

      - name: List release files
        run: ls -al release
